// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: measures.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ch.heigvd.iict.dma.protobuf;

